version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    links:
      - db
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: 'mysql2://${DB_USER}:@${DB_HOST}/${DB_NAME}?encoding=${DB_ENCODING}&collation=${DB_COLLATION}'
    # command: sh -c './bin/wait-for db:3306 -- bundle exec rerun -- rackup --host 0.0.0.0'
    command: './bin/wait-for-it.sh db:3306 -- bundle exec rerun -- rackup --host 0.0.0.0'
    ports:
      - '9292:9292'
  db:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
  bundle:
    driver: local
